export type GalleryItem = {
  id: string;
  src: string;
  alt: string;
  /**
   * Used for a 3-up justified row layout.
   * Higher number = wider image within the row.
   */
  ratio: number;
  /**
   * Object fit for the image: 'cover' or 'contain'.
   */
  objectFit?: 'cover' | 'contain';
  /**
   * Description for the image, used on single image pages.
   */
  description?: string;
  createtime: string;
  category?: string;
  
};

// Pexels examples (you can swap/add more). We vary span + aspect for a dynamic layout.
export const galleryItems: GalleryItem[] = [
  {
    id: "p1",
    // src: "https://images.pexels.com/photos/35051828/pexels-photo-35051828.jpeg",
    src: "https://artwork-hub.vercel.app/images/catwithrain.jpg",
    alt: "Rainy Day Cat Parade",
    ratio: 1.5,
    createtime: "2024-12-24",
    category: "animal",
    description: "A whimsical illustration of cats enjoying a rainy day, capturing the joy and playfulness in unexpected weather.",
  },
  {
    id: "p2",
    src: "https://artwork-hub.vercel.app/images/duckriver.jpg",
    alt: "Gentle Afternoon by the River",
    description: "A serene scene of ducks gliding through a peaceful river, showcasing the beauty of nature in a quiet moment.",
    ratio: 0.9,
    createtime: "2024-12-24",
    category: "animal",
  },
  {
    id: "p3",
    src: "https://artwork-hub.vercel.app/images/farmer.jpg",
    alt: "River Through the Sheep Fields",
    description: "A charming depiction of a river winding through a lush field of sheep, evoking a sense of tranquility and rural charm.",
    ratio: 1.2,
    createtime: "2024-12-24",
    category: "landscape",
  },
  {
    id: "p4",
    src: "https://artwork-hub.vercel.app/images/fish.jpg",
    alt: "Goldfish Among the Water Lilies",
    description: "A delicate illustration of goldfish swimming among water lilies, highlighting the delicate balance of aquatic life.",
    ratio: 0.85,
    createtime: "2024-12-20",
    category: "animal",
  },
  {
    id: "p5",
    src: "https://artwork-hub.vercel.app/images/flowers.jpg",
    alt: "Garden in Full Bloom",
    description: "A vibrant portrayal of a garden bursting with colorful flowers, capturing the essence of spring and natural beauty.",
    ratio: 0.95,
    createtime: "2024-12-22",
    category: "plant",
  },
  {
    id: "p6",
    src: "https://artwork-hub.vercel.app/images/fluffyballs.jpg",
    alt: "Fluffy Friends Chatting",
    description: "A playful scene of fluffy animals gathered together, sharing stories and laughter in a cozy setting.",
    ratio: 1.5,
    createtime: "2024-12-24",
    category: "animal",
  },
  {
    id: "p7",
    src: "https://artwork-hub.vercel.app/images/greendog.jpg",
    alt: "Pond Pals in Clover",
    description: "A heartwarming illustration of dogs lounging by a pond, surrounded by lush greenery and golden sunlight.",
    ratio: 1.1,
    createtime: "2024-12-23",
    category: "animal",
  },
  {
    id: "p8",
    src: "https://artwork-hub.vercel.app/images/labubu.jpg",
    alt: "Purple Labubu Grin",
    description: "A playful character named Labubu with a cheerful grin, embodying joy and mischief in a whimsical style.",
    ratio: 0.77,
    createtime: "2024-12-17",
    category: "figure",
  },
  {
    id: "p9",
    src: "https://artwork-hub.vercel.app/images/plant.jpg",
    alt: "Trees on the Sunny Hill",
    description: "A peaceful landscape of trees standing tall on a sunny hill, reflecting the beauty of nature's harmony.",
    ratio: 1.56,
    createtime: "2024-12-21",
    category: "plant",
  },
  {
    id: "p10",
    src: "https://artwork-hub.vercel.app/images/redroofcat.jpg",
    alt: "Cat on the Autumn Roof",
    description: "A cozy scene of a cat perched on a red roof, surrounded by autumn leaves and a warm, inviting atmosphere.",
    ratio: 1.1,
    createtime: "2024-12-23",
    category: "animal",
  },
  {
    id: "p11",
    src: "https://artwork-hub.vercel.app/images/sakura.jpg",
    alt: "Path Under the Cherry Blossoms",
    description: "A serene path lined with cherry blossoms, creating a magical and ethereal atmosphere in the springtime.",
    ratio: 0.7,
    createtime: "2024-12-17",
    category: "plant",
  },
  {
    id: "p12",
    src: "https://artwork-hub.vercel.app/images/winter.jpg",
    alt: "Quiet Cabin in the Snow",
    description: "A tranquil winter scene featuring a cozy cabin nestled in the snow, evoking warmth and solitude.",
    ratio: 0.77,
    createtime: "2024-12-10",
    category: "landscape",
  },
  {
    id: "p13",
    src: "https://artwork-hub.vercel.app/images/sunsetcat.jpg",
    alt: "Dusk and the Cat",
    description: "A beautiful sunset scene with a cat enjoying the golden hour, capturing the magic of twilight.",
    ratio: 1.0,
    createtime: "2024-12-23",
    category: "animal",
  },
  {
    id: "p14",
    src: "https://artwork-hub.vercel.app/images/shiba_frog.jpg",
    alt: "shiba and Frog Chat",
    description: "A cute shiba and frog chatting",
    ratio: 0.8,
    createtime: "2024-12-15",
    category: "animal",
  },
  {
    id: "p15",
    src: "https://artwork-hub.vercel.app/images/pinkboy.jpg",
    alt: "Autumn Walk with a Dragon Friend",
    description: "A charming autumn walk with a dragon friend, blending nature and fantasy in a delightful scene.",
    ratio: 1.45,
    createtime: "2024-12-18",
    category: "animal",
  },
  {
    id: "p16",
    src: "https://artwork-hub.vercel.app/images/autum.jpg",
    alt: "Colors of the Fall Canopy",
    description: "Vibrant colors of the fall canopy, showcasing the beauty of autumn foliage in a breathtaking display.",
    ratio: 1.4,
    createtime: "2024-12-20",
    category: "plant",
  },
  {
    id: "p17",
    src: "https://artwork-hub.vercel.app/images/beach.jpg",
    alt: "Sailing Into Sunset Dreams",
    description: "A peaceful sailing adventure into sunset dreams, capturing the serene beauty of a boat gliding across the water at dusk.",
    ratio: 0.65,
    createtime: "2024-12-17",
    category: "landscape",
  },
  {
    id: "p18",
    src: "https://artwork-hub.vercel.app/images/bear.jpg",
    alt: "Surprised Cat and Cozy Reindeer",
    description: "A surprised cat and a cozy reindeer sharing a moment of warmth and friendship in a whimsical setting.",
    ratio: 1.45,
    createtime: "2024-12-22",
    category: "animal",
  },
  {
    id: "p19",
    src: "https://artwork-hub.vercel.app/images/catplay.jpg",
    alt: "Sunset Swing With You",
    description: "A romantic sunset swing with you, capturing the beauty of a couple enjoying a peaceful moment together.",
    ratio: 0.73,
    createtime: "2024-12-19",
    category: "animal",
  },
    {
    id: "p20",
    src: "https://artwork-hub.vercel.app/images/bag.jpg",
    alt: "Cute Bag",
    description: "A cute bag",
    ratio: 1.11,
    createtime: "2025-12-23",
    category: "plant",
  },
  {
    id: "p21",
    src: "https://artwork-hub.vercel.app/images/cabin.jpg",
    alt: "Cabin in the Snow",
    description: "A cabin in the snow",
    ratio: 0.9,
    createtime: "2025-12-19",
    category: "landscape",
  },
  {
    id: "p22",
    src: "https://artwork-hub.vercel.app/images/dogcar.jpg",
    alt: "Dog Car Ride",
    description: "A dog car ride",
    ratio: 1.0,
    createtime: "2026-1-3",
    category: "animal",
  },
  {
    id: "p23",
    src: "https://artwork-hub.vercel.app/images/ducksleep.jpg",
    alt: "Duck sleeping",
    ratio: 1.0,
    createtime: "2025-12-20",
    category: "animal",
  },
  {
    id: "p24",
    src: "https://artwork-hub.vercel.app/images/goose.jpg",
    alt: "Child with Goose",
    ratio: 1.1,
    createtime: "2025-12-15",
    category: "animal",
  },
  {
    id: "p25",
    src: "https://artwork-hub.vercel.app/images/manycats.jpg",
    alt: "Many Cats Gathered",
    ratio: 0.96,
    createtime: "2025-12-15",
    category: "animal",
  },
  {
    id: "p26",
    src: "https://artwork-hub.vercel.app/images/moutain.jpg",
    alt: "Moutain View",
    ratio: 0.65,
    objectFit: 'contain',
    createtime: "2026-1-2",
    category: "landscape",
  },
  {
    id: "p27",
    src: "https://artwork-hub.vercel.app/images/nightview.jpg",
    alt: "Night View",
    ratio: 1.0,
    createtime: "2025-12-31",
    category: "landscape",
  },
  {
    id: "p28",
    src: "https://artwork-hub.vercel.app/images/phonebox.jpg",
    alt: "London Phone Box",
    ratio: 0.53,
    objectFit: 'contain',
    createtime: "2025-12-26",
    category: "landscape",
  },
  {
    id: "p29",
    src: "https://artwork-hub.vercel.app/images/redgirl.jpg",
    alt: "Girl in Red Coat",
    ratio: 0.7,
    createtime: "2025-12-25",
    category: "figure",
  },
  {
    id: "p30",
    src: "https://artwork-hub.vercel.app/images/sakura2.jpg",
    alt: "sakura with clouds",
    ratio: 1.0,
    createtime: "2025-12-17",
  },
  {
    id: "p31",
    src: "https://artwork-hub.vercel.app/images/sheeppatern.jpg",
    alt: "Yellow Sheep Pattern",
    ratio: 1.1,
    createtime: "2025-12-19",
    category: "animal",
  },
  {
    id: "p32",
    src: "https://artwork-hub.vercel.app/images/sheeps.jpg",
    alt: "Sheeps in the Field",
    ratio: 1.05,
    createtime: "2025-12-25",
    category: "animal",
  },
  {
    id: "p33",
    src: "https://artwork-hub.vercel.app/images/snowman2.jpg",
    alt: "Snowman with Scarf",
    ratio: 0.94,
    createtime: "2025-12-17",
  },
  {
    id: "p34",
    src: "https://artwork-hub.vercel.app/images/snowtemple.jpg",
    alt: "Snow Temple",
    ratio: 0.35,
    objectFit: 'contain',
    createtime: "2025-12-25",
    category: "landscape",
  },
  {
    id: "p35",
    src: "https://artwork-hub.vercel.app/images/twocatswithmoon.jpg",
    alt: "Two Cats Sitting under the Moon",
    ratio: 1.1,
    createtime: "2025-12-21",
    category: "animal",
  },
  {
    id: "p36",
    src: "https://artwork-hub.vercel.app/images/whitebird.jpg",
    alt: "Red-frowned crane",
    ratio: 0.98,
    createtime: "2025-12-30",
    category: "animal",
  },
  {
    id: "p37",
    src: "https://artwork-hub.vercel.app/images/animal.jpg",
    alt: "Animal Friends",
    ratio: 0.45,
    createtime: "2025-12-22",
    category: "animal",
  },
  {
    id: "p38",
    src: "https://artwork-hub.vercel.app/images/beach2.jpg",
    alt: "Nice Beach",
    ratio: 0.48,
    objectFit: 'contain',
    createtime: "2026-1-10",
    category: "landscape",
  },
  {
    id: "p39",
    src: "https://artwork-hub.vercel.app/images/bluehairgirls.jpg",
    alt: "blue hair girl",
    ratio: 1.2,
    createtime: "2026-1-5",
    category: "figure",
  },
  {
    id: "p40",
    src: "https://artwork-hub.vercel.app/images/fluffyball2.jpg",
    alt: "fluffy ball friends",
    ratio: 0.8,
    createtime: "2026-1-2",
    category: "animal",
  },
  {
    id: "p41",
    src: "https://artwork-hub.vercel.app/images/girlcarry.jpg",
    alt: "girl carrying flowers",
    ratio: 1.18,
    createtime: "2026-1-2",
    category: "figure",
  },
  {
    id: "p42",
    src: "https://artwork-hub.vercel.app/images/goodbear.jpg",
    alt: "good bear",
    ratio: 1.0,
    createtime: "2026-1-3",
    category: "animal",
  },
  {
    id: "p43",
    src: "https://artwork-hub.vercel.app/images/mansea.jpg",
    alt: "man by the sea",
    ratio: 1.1,
    createtime: "2025-12-22",
    category: "landscape",
  },
  {
    id: "p44",
    src: "https://artwork-hub.vercel.app/images/nightview2.jpg",
    alt: "peaceful night view",
    createtime: "2025-12-29",
    ratio: 1.5,
    category: "landscape",
  },
  {
    id: "p45",
    src: "https://artwork-hub.vercel.app/images/pinkbeach.jpg",
    alt: "peaceful beach",
    objectFit: 'contain',
    ratio: 1.2,
    createtime: "2025-12-28",
    category: "landscape",
  },
  {
    id: "p46",
    src: "https://artwork-hub.vercel.app/images/sunset.jpg",
    alt: "sunset view",
    ratio: 1.2,
    createtime: "2025-12-18",
    category: "landscape",
  },
  {
    id: "p47",
    src: "https://artwork-hub.vercel.app/images/watermelon.jpg",
    alt: "duck swimming in watermelon pool",
    ratio: 1.2,
    createtime: "2026-1-3",
    category: "fruit",
  },
  {
    id: "p48",
    src: "https://artwork-hub.vercel.app/images/whitedog.jpg",
    alt: "white dog",
    ratio: 1.1,
    createtime: "2025-12-27",
    category: "animal",
  },
  {
    id: "p49",
    src: "https://artwork-hub.vercel.app/images/wintercabin.jpg",
    alt: "man walking in winter cabin",
    ratio: 1.15,
    createtime: "2025-12-18",
    category: "landscape",
  },

  {
    id: "p51",
    src: "https://artwork-hub.vercel.app/images/whales.jpg",
    alt: "different whales",
    ratio: 1.2,
    createtime: "2026-1-4",
    category: "animal",
  },
  {
    id: "p52",
    src: "https://artwork-hub.vercel.app/images/hangingduck.jpg",
    alt: "hanging duck",
    ratio: 1.2,
    createtime: "2025-12-15",
  },
  {
    id: "p53",
    src: "https://artwork-hub.vercel.app/images/banana.jpg",
    alt: "cute banana",
    ratio: 1.2,
    createtime: "2025-12-15",
    category: "fruit",
  },
  {
    id: "p54",
    src: "https://artwork-hub.vercel.app/images/beach3.jpg",
    alt: "nice beach view",
    ratio: 1.2,
    createtime: "2025-12-21",
    category: "landscape",
  },
  {
    id: "p55",
    src: "https://artwork-hub.vercel.app/images/blackdoor.jpg",
    alt: "black door",
    ratio: 1.1,
    createtime: "2025-12-21",
    category: "plant",
  },
  {
    id: "p56",
    src: "https://artwork-hub.vercel.app/images/boysleep.jpg",
    alt: "boy sleeping",
    ratio: 0.98,
    createtime: "2026-1-7",
    category: "figure",
  },
  {
    id: "p57",
    src: "https://artwork-hub.vercel.app/images/boysplay.jpg",
    alt: "chase butterflies",
    ratio: 1.0,
    createtime: "2026-1-5",
    category: "landscape",
  },
  {
    id: "p58",
    src: "https://artwork-hub.vercel.app/images/colorsheep.jpg",
    alt: "sheep with colorful wool",
    ratio: 1.0,
    createtime: "2026-1-6",
    category: "animal",
  },
  {
    id: "p59",
    src: "https://artwork-hub.vercel.app/images/doggrass.jpg",
    alt: "dog in the grass",
    ratio: 1.1,
    createtime: "2026-1-5",
    category: "animal",
  },
  {
    id: "p60",
    src: "https://artwork-hub.vercel.app/images/dogrunning.jpg",
    alt: "dog running",
    ratio: 1.0,
    createtime: "2026-1-8",
    category: "animal",
  },
  {
    id: "p61",
    src: "https://artwork-hub.vercel.app/images/dogsleep.jpg",
    alt: "dog is sleeping",
    ratio: 1.0,
    createtime: "2026-1-4",
    category: "animal",
  },
  {
    id: "p62",
    src: "https://artwork-hub.vercel.app/images/girlcat.jpg",
    alt: "girl is sitting with cat",
    ratio: 1.4,
    createtime: "2026-1-6",
    category: "figure",
  },
  {
    id: "p63",
    src: "https://artwork-hub.vercel.app/images/girlhat.jpg",
    alt: "girl with hat",
    ratio: 1.0,
    createtime: "2026-1-5",
    category: "figure",
  },
  {
    id: "p64",
    src: "https://artwork-hub.vercel.app/images/girlsmile.jpg",
    alt: "girl is smiling",
    ratio: 1.0,
    createtime: "2026-1-9",
    category: "figure",
  },
  {
    id: "p65",
    src: "https://artwork-hub.vercel.app/images/horse.jpg",
    alt: "horse in the field",
    ratio: 0.45,
    createtime: "2026-1-13",
    category: "animal",
  },
  {
    id: "p66",
    src: "https://artwork-hub.vercel.app/images/horse2026.jpg",
    alt: "horse celebration 2026",
    ratio: 1.3,
    createtime: "2026-1-7",
    category: "animal",
  },
  {
    id: "p67",
    src: "https://artwork-hub.vercel.app/images/jiqimao.jpg",
    alt: "machine cat",
    ratio: 1.0,
    createtime: "2026-1-5",
    category: "animal",
  },
  {
    id: "p68",
    src: "https://artwork-hub.vercel.app/images/lamp.jpg",  
    alt: "lamp",
    ratio: 0.9,
    createtime: "2026-1-5",
    category: "object",
  },
  {
    id: "p69",
    src: "https://artwork-hub.vercel.app/images/pinkcat.jpg",
    alt: "cat with glasses",
    ratio: 1.1,
    createtime: "2026-1-4",
    category: "animal",
  },
  {
    id: "p70",
    src: "https://artwork-hub.vercel.app/images/planewindow.jpg",
    alt: "window seat view",
    ratio: 1.0,
    createtime: "2026-1-6",
    category: "landscape",
  },
  {
    id: "p71",
    src: "https://artwork-hub.vercel.app/images/sakuratree.jpg",
    alt: "sakura tree",
    ratio: 1.5,
    createtime: "2026-1-6",
    category: "plant",
  },
  {
    id: "p72",
    src: "https://artwork-hub.vercel.app/images/snowcabin.jpg",
    alt: "cabins in the snow",
    ratio: 1.0,
    createtime: "2026-1-7",
    category: "landscape",
  },
  {
    id: "p73",
    src: "https://artwork-hub.vercel.app/images/socks.jpg",
    alt: "hanging socks",
    ratio: 1.0,
    createtime: "2026-1-14",
    category: "object",
  },
  {
    id: "p74",
    src: "https://artwork-hub.vercel.app/images/whitecatstar.jpg",
    alt: "cat is playing with star",
    ratio: 1.08,
    createtime: "2026-1-14",
    category: "animal",
  },
  {
    id: "p75",
    src: "https://artwork-hub.vercel.app/images/whitesheep.jpg",
    alt: "white sheep",
    ratio: 1.0,
    createtime: "2026-1-11",
    category: "animal",
  },
  {
    id: "p76",
    src: "https://artwork-hub.vercel.app/images/fengche.jpg",
    alt: "windmill",
    ratio: 1.0,
    createtime: "2026-1-17",
    category: "landscape",
  },
  {
    id: "p77",
    src: "https://artwork-hub.vercel.app/images/guilin.jpg",
    alt: "guilin landscape",
    ratio: 1.0,
    createtime: "2026-1-17",
    category: "landscape",
  },
  {
    id: "p78",
    src: "https://artwork-hub.vercel.app/images/colorfulcloth.jpg",
    alt: "a girl with colorful cloth",
    ratio: 1.3,
    createtime: "2026-1-17",
    category: "figure",
  },
  {
    id: "p79",
    src: "https://artwork-hub.vercel.app/images/yellowgirl.jpg",
    alt: "a girl in yellow dress",
    ratio: 1.0,
    createtime: "2026-1-30",
    category: "figure",
  },
  {
    id: "p80",
    src: "https://artwork-hub.vercel.app/images/catlookfish.jpg",
    alt: "a cat looking at fish",
    ratio: 0.9,
    createtime: "2026-1-31",
    category: "animal",
  },
  {
    id: "p81",
    src: "https://artwork-hub.vercel.app/images/mermid.jpg",
    alt: "mermid",
    ratio: 1.1,
    createtime: "2026-1-31",
    category: "figure",
  },
  {
    id: "p82",
    src: "https://artwork-hub.vercel.app/images/sunflower.jpg",
    alt: "sunflower growing",
    ratio: 1.0,
    createtime: "2026-2-2",
    category: "plant",
  },
  {
    id: "p83",
    src: "https://artwork-hub.vercel.app/images/yellowflower.jpg",
    alt: "yellow flower with house",
    ratio: 1.5,
    createtime: "2026-2-2",
    category: "landscape",
  },
  {
    id: "p84",
    src: "https://artwork-hub.vercel.app/images/denglong.jpg",
    alt: "red lanterns",
    ratio: 1.0,
    createtime: "2026-2-3",
    category: "object",
  },
  {
    id: "p85",
    src: "https://artwork-hub.vercel.app/images/moon.jpg",
    alt: "full moon night",
    ratio: 0.7,
    createtime: "2026-2-3",
    category: "landscape",
  },
  {
    id: "p86",
    src: "https://artwork-hub.vercel.app/images/catfish.jpg",
    alt: "cat and fish",
    ratio: 1.0,
    createtime: "2026-2-3",
    category: "animal",
  },
  {
    id: "p87",
    src: "https://artwork-hub.vercel.app/images/bluegirl.jpg",
    alt: "blue hair girl",
    ratio: 1.0,
    createtime: "2026-2-3",
    category: "figure",
  },
  {
    id: "p88",
    src: "https://artwork-hub.vercel.app/images/park.jpg",
    alt: "park view",
    ratio: 0.6,
    createtime: "2025-12-19",
    category: "landscape",
  },
  {
    id: "p89",
    src: "https://artwork-hub.vercel.app/images/snail.jpg",
    alt: "cute snail",
    ratio: 1.0,
    createtime: "2025-12-19",
    category: "animal",
  },
  {
    id: "p90",
    src: "https://artwork-hub.vercel.app/images/twocats.jpg",
    alt: "two cats sitting together under the autumn tree",
    ratio: 1.1,
    createtime: "2025-12-16",
    category: "animal",
  },
  {
    id: "p91",
    src: "https://artwork-hub.vercel.app/images/bluecat.jpg",
    alt: "blue cat",
    ratio: 1.0,
    createtime: "2025-12-16",
    category: "animal",
  },
  {
    id: "p92",
    src: "https://artwork-hub.vercel.app/images/beachview.jpg",
    alt: "beach view",
    ratio: 1.0,
    createtime: "2025-12-15",
    category: "landscape",
  },
  {
    id: "p93",
    src: "https://artwork-hub.vercel.app/images/shipview.jpg",
    alt: "ship view",
    ratio: 1.6,
    createtime: "2025-12-28",
    category: "landscape",
  },
  {
    id: "p94",
    src: "https://artwork-hub.vercel.app/images/moutainview.jpg",
    alt: "mountain view",
    ratio: 1.0,
    createtime: "2025-12-28",
    category: "landscape",
  },
  {
    id: "p95",
    src: "https://artwork-hub.vercel.app/images/xianrenzhang.jpg",
    alt: "plant leaf",
    ratio: 1.0,
    createtime: "2025-12-24",
    category: "plant",
  },
  {
    id: "p96",
    src: "https://artwork-hub.vercel.app/images/sheepsplay.jpg",
    alt: "sheeps playing",
    ratio: 1.0,
    createtime: "2025-12-28",
    category: "animal",
  },
  {
    id: "p97",
    src: "https://artwork-hub.vercel.app/images/catlookingfirework.jpg",
    alt: "cat looking at firework",
    ratio: 1.0,
    createtime: "2026-1-6",
    category: "animal",
  },
  {
    id: "p98",
    src: "https://artwork-hub.vercel.app/images/humans.jpg",
    alt: "different humans",
    ratio: 1.0,
    createtime: "2025-12-23",
    category: "figure",
  },
  {
    id: "p99",
    src: "https://artwork-hub.vercel.app/images/changjinlu.jpg",
    alt: "giraffe standing",
    ratio: 1.0,
    createtime: "2025-12-31",
    category: "animal",
  },
  {
    id: "p100",
    src: "https://artwork-hub.vercel.app/images/pugongying.jpg",
    alt: "dandelion flower",
    ratio: 1.0,
    createtime: "2025-12-20",
    category: "plant",
  },
  {
    id: "p101",
    src: "https://artwork-hub.vercel.app/images/bigtree.jpg",
    alt: "big tree",
    ratio: 1.6,
    createtime: "2025-12-29",
    category: "plant",
  },
  {
    id: "p102",
    src: "https://artwork-hub.vercel.app/images/book.jpg",
    alt: "book with tomato",
    ratio: 1.1,
    createtime: "2025-12-31",
    category: "object",
  },
  {
    id: "p103",
    src: "https://artwork-hub.vercel.app/images/sunset2.jpg",
    alt: "sunset sky",
    ratio: 1.0,
    createtime: "2025-12-30",
    category: "landscape",
  },
  {
    id: "p104",
    src: "https://artwork-hub.vercel.app/images/shuiguo.jpg",
    alt: "fruits world",
    ratio: 1.0,
    createtime: "2025-12-30",
    category: "fruit",
  },
  {
    id: "p105",
    src: "https://artwork-hub.vercel.app/images/xigua.jpg",
    alt: "watermelon slice",
    ratio: 1.0,
    createtime: "2026-1-1",
    category: "fruit",
  },
  {
    id: "p106",
    src: "https://artwork-hub.vercel.app/images/newyear.jpg",
    alt: "new year 2026",
    ratio: 1.0,
    createtime: "2026-1-1",
    category: "figure",
  },

  {
    id: "p107",
    src: "https://artwork-hub.vercel.app/images/tank.jpg",
    alt: "tank",
    ratio: 1.0,
    createtime: "2026-2-5",
    category: "object",
  },

  {
    id: "p108",
    src: "https://artwork-hub.vercel.app/images/awhitesheep.jpg",
    alt: "a white sheep",
    ratio: 1.07,
    createtime: "2026-02-06",
    category: "animal",
  },

  {
    id: "p109",
    src: "https://artwork-hub.vercel.app/images/aguineapig.jpg",
    alt: "a guinea pig",
    ratio: 0.88,
    createtime: "2026-02-06",
    category: "animal",
  },

  {
    id: "p110",
    src: "https://artwork-hub.vercel.app/images/redcatholdtree.jpg",
    alt: "a red cat holding a tree",
    ratio: 1.02,
    createtime: "2026-02-06",
    category: "animal",
  },

  {
    id: "p111",
    src: "https://artwork-hub.vercel.app/images/daisy.jpg",
    alt: "daisy",
    ratio: 1.01,
    createtime: "2026-02-06",
    category: "plant",
  },

  {
    id: "p112",
    src: "https://artwork-hub.vercel.app/images/daisyview.jpg",
    alt: "pink daisy view",
    ratio: 0.51,
    createtime: "2026-02-08",
    category: "plant",
  },

  {
    id: "p113",
    src: "https://artwork-hub.vercel.app/images/gateview.jpg",
    alt: "gate view",
    ratio: 0.98,
    createtime: "2026-02-08",
    category: "landscape",
  },

  {
    id: "p114",
    src: "https://artwork-hub.vercel.app/images/greenview.jpg",
    alt: "green view",
    ratio: 1.02,
    createtime: "2026-02-08",
    category: "landscape",
  },

  {
    id: "p115",
    src: "https://artwork-hub.vercel.app/images/newyearnightview.jpg",
    alt: "new year night view",
    ratio: 0.54,
    createtime: "2026-02-08",
    category: "landscape",
  },

  {
    id: "p116",
    src: "https://artwork-hub.vercel.app/images/springviewhouse.jpg",
    alt: "spring view house",
    ratio: 0.49,
    createtime: "2026-02-08",
    category: "landscape",
  },



























];
