export type GalleryItem = {
  id: string;
  src: string;
  thumbSrc?: string;
  alt: string;
  /**
   * Used for a 3-up justified row layout.
   * Higher number = wider image within the row.
   */
  ratio: number;
  /**
   * Object fit for the image: 'cover' or 'contain'.
   */
  objectFit?: 'cover' | 'contain';
  /**
   * Description for the image, used on single image pages.
   */
  description?: string;
  createtime: string;
  category?: string;
  tag?: string;
  
};

// Pexels examples (you can swap/add more). We vary span + aspect for a dynamic layout.
const rawGalleryItems: GalleryItem[] = [
  {
    id: "p1",
    // src: "https://images.pexels.com/photos/35051828/pexels-photo-35051828.jpeg",
    src: "https://artwork-hub.vercel.app/images/catwithrain.jpg",
    alt: "Rainy Day Cat Parade",
    ratio: 1.5,
    createtime: "2024-12-24",
    category: "animal",
    tag: "cat",
    description: "A whimsical illustration of cats enjoying a rainy day, capturing the joy and playfulness in unexpected weather.",
  },
  {
    id: "p2",
    src: "https://artwork-hub.vercel.app/images/duckriver.jpg",
    alt: "Gentle Afternoon by the River",
    description: "A serene scene of ducks gliding through a peaceful river, showcasing the beauty of nature in a quiet moment.",
    ratio: 0.9,
    createtime: "2024-12-24",
    category: "animal",
    tag: "duck",
  },
  {
    id: "p3",
    src: "https://artwork-hub.vercel.app/images/farmer.jpg",
    alt: "River Through the Sheep Fields",
    description: "A charming depiction of a river winding through a lush field of sheep, evoking a sense of tranquility and rural charm.",
    ratio: 0.7,
    createtime: "2024-12-24",
    category: "landscape",
    tag: "sheep",
  },
  {
    id: "p4",
    src: "https://artwork-hub.vercel.app/images/fish.jpg",
    alt: "Goldfish Among the Water Lilies",
    description: "A delicate illustration of goldfish swimming among water lilies, highlighting the delicate balance of aquatic life.",
    ratio: 0.85,
    createtime: "2024-12-20",
    category: "animal",
    tag: "fish",
  },
  {
    id: "p5",
    src: "https://artwork-hub.vercel.app/images/flowers.jpg",
    alt: "Garden in Full Bloom",
    tag: "flower",
    description: "A vibrant portrayal of a garden bursting with colorful flowers, capturing the essence of spring and natural beauty.",
    ratio: 0.95,
    createtime: "2024-12-22",
    category: "plant",
  },
  {
    id: "p6",
    src: "https://artwork-hub.vercel.app/images/fluffyballs.jpg",
    alt: "Fluffy Friends Chatting",
    tag: "fluffy",
    description: "A playful scene of fluffy animals gathered together, sharing stories and laughter in a cozy setting.",
    ratio: 1.75,
    createtime: "2024-12-24",
    category: "animal",
  },
  {
    id: "p7",
    src: "https://artwork-hub.vercel.app/images/greendog.jpg",
    alt: "Pond Pals in Clover",
    tag: "dog",
    description: "A heartwarming illustration of dogs lounging by a pond, surrounded by lush greenery and golden sunlight.",
    ratio: 1.1,
    createtime: "2024-12-23",
    category: "animal",
  },
  {
    id: "p8",
    src: "https://artwork-hub.vercel.app/images/labubu.jpg",
    alt: "Purple Labubu Grin",
    tag: "labubu",
    description: "A playful character named Labubu with a cheerful grin, embodying joy and mischief in a whimsical style.",
    ratio: 0.68,
    createtime: "2024-12-17",
    category: "figure",
  },
  {
    id: "p9",
    src: "https://artwork-hub.vercel.app/images/plant.jpg",
    alt: "Trees on the Sunny Hill",
    tag: "tree",
    description: "A peaceful landscape of trees standing tall on a sunny hill, reflecting the beauty of nature's harmony.",
    ratio: 1.56,
    createtime: "2024-12-21",
    category: "plant",
  },
  {
    id: "p10",
    src: "https://artwork-hub.vercel.app/images/redroofcat.jpg",
    alt: "Cat on the Autumn Roof",
    tag: "cat and spring",
    description: "A cozy scene of a cat perched on a red roof, surrounded by autumn leaves and a warm, inviting atmosphere.",
    ratio: 1.1,
    createtime: "2024-12-23",
    category: "animal",
  },
  {
    id: "p11",
    src: "https://artwork-hub.vercel.app/images/sakura.jpg",
    alt: "Path Under the Cherry Blossoms",
    tag: "sakura",
    description: "A serene path lined with cherry blossoms, creating a magical and ethereal atmosphere in the springtime.",
    ratio: 0.7,
    createtime: "2024-12-17",
    category: "plant",
  },
  {
    id: "p12",
    src: "https://artwork-hub.vercel.app/images/winter.jpg",
    alt: "Quiet Cabin in the Snow",
    tag: "cabin",
    description: "A tranquil winter scene featuring a cozy cabin nestled in the snow, evoking warmth and solitude.",
    ratio: 0.77,
    createtime: "2024-12-10",
    category: "landscape",
  },
  {
    id: "p13",
    src: "https://artwork-hub.vercel.app/images/sunsetcat.jpg",
    alt: "Dusk and the Cat",
    tag: "cat",
    description: "A beautiful sunset scene with a cat enjoying the golden hour, capturing the magic of twilight.",
    ratio: 1.0,
    createtime: "2024-12-23",
    category: "animal",
  },
  {
    id: "p14",
    src: "https://artwork-hub.vercel.app/images/shiba_frog.jpg",
    alt: "shiba and Frog Chat",
    tag: "shiba",
    description: "A cute shiba and frog chatting",
    ratio: 0.8,
    createtime: "2024-12-15",
    category: "animal",
  },
  {
    id: "p15",
    src: "https://artwork-hub.vercel.app/images/pinkboy.jpg",
    alt: "Autumn Walk with a Dragon Friend",
    tag: "dragon",
    description: "A charming autumn walk with a dragon friend, blending nature and fantasy in a delightful scene.",
    ratio: 1.45,
    createtime: "2024-12-18",
    category: "animal",
  },
  {
    id: "p16",
    src: "https://artwork-hub.vercel.app/images/autum.jpg",
    alt: "Colors of the Fall Canopy",
    tag: "autumn",
    description: "Vibrant colors of the fall canopy, showcasing the beauty of autumn foliage in a breathtaking display.",
    ratio: 1.4,
    createtime: "2024-12-20",
    category: "plant",
  },
  {
    id: "p17",
    src: "https://artwork-hub.vercel.app/images/beach.jpg",
    alt: "Sailing Into Sunset Dreams",
    tag: "beach",
    description: "A peaceful sailing adventure into sunset dreams, capturing the serene beauty of a boat gliding across the water at dusk.",
    ratio: 0.65,
    createtime: "2024-12-17",
    category: "landscape",
  },
  {
    id: "p18",
    src: "https://artwork-hub.vercel.app/images/bear.jpg",
    alt: "Surprised Cat and Cozy Reindeer",
    tag: "cat and reindeer",
    description: "A surprised cat and a cozy reindeer sharing a moment of warmth and friendship in a whimsical setting.",
    ratio: 1.45,
    createtime: "2024-12-22",
    category: "animal",
  },
  {
    id: "p19",
    src: "https://artwork-hub.vercel.app/images/catplay.jpg",
    alt: "Sunset Swing With You",
    tag: "cat",
    description: "A romantic sunset swing with you, capturing the beauty of a couple enjoying a peaceful moment together.",
    ratio: 0.73,
    createtime: "2024-12-19",
    category: "animal",
  },
    {
    id: "p20",
    src: "https://artwork-hub.vercel.app/images/bag.jpg",
    alt: "Cute Bag",
    tag: "bag",
    description: "A cute bag",
    ratio: 1.11,
    createtime: "2025-12-23",
    category: "plant",
  },
  {
    id: "p21",
    src: "https://artwork-hub.vercel.app/images/cabin.jpg",
    alt: "Cabin in the Snow",
    tag: "cabin",
    description: "A cabin in the snow",
    ratio: 0.9,
    createtime: "2025-12-19",
    category: "landscape",
  },
  {
    id: "p22",
    src: "https://artwork-hub.vercel.app/images/dogcar.jpg",
    alt: "Dog Car Ride",
    tag: "dog",
    description: "A dog car ride",
    ratio: 1.0,
    createtime: "2026-1-3",
    category: "animal",
  },
  {
    id: "p23",
    src: "https://artwork-hub.vercel.app/images/ducksleep.jpg",
    tag: "duck",
    alt: "Duck sleeping",
    ratio: 1.0,
    createtime: "2025-12-20",
    category: "animal",
  },
  {
    id: "p24",
    src: "https://artwork-hub.vercel.app/images/goose.jpg",
    tag: "goose",
    alt: "Child with Goose",
    ratio: 1.1,
    createtime: "2025-12-15",
    category: "animal",
  },
  {
    id: "p25",
    src: "https://artwork-hub.vercel.app/images/manycats.jpg",
    tag: "cat",
    alt: "Many Cats Gathered",
    ratio: 0.96,
    createtime: "2025-12-15",
    category: "animal",
  },
  {
    id: "p26",
    src: "https://artwork-hub.vercel.app/images/moutain.jpg",
    tag: "mountain and sea",
    alt: "Mountain View",
    ratio: 0.65,
    objectFit: 'contain',
    createtime: "2026-1-2",
    category: "landscape",
  },
  {
    id: "p27",
    src: "https://artwork-hub.vercel.app/images/nightview.jpg",
    tag: "nightview with trees and sky",
    alt: "Night View",
    ratio: 1.0,
    createtime: "2025-12-31",
    category: "landscape",
  },
  {
    id: "p28",
    src: "https://artwork-hub.vercel.app/images/phonebox.jpg",
    tag: "phonebox",
    alt: "London Phone Box",
    ratio: 0.53,
    objectFit: 'contain',
    createtime: "2025-12-26",
    category: "landscape",
  },
  {
    id: "p29",
    src: "https://artwork-hub.vercel.app/images/redgirl.jpg",
    tag: "red girl",
    alt: "Girl in Red Coat",
    ratio: 0.7,
    createtime: "2025-12-25",
    category: "figure",
  },
  {
    id: "p30",
    src: "https://artwork-hub.vercel.app/images/sakura2.jpg",
    tag: "sakura",
    alt: "sakura with clouds",
    ratio: 1.0,
    createtime: "2025-12-17",
  },
  {
    id: "p31",
    src: "https://artwork-hub.vercel.app/images/sheeppattern.jpg",
    tag: "sheep",
    alt: "Yellow Sheep Pattern",
    ratio: 1.1,
    createtime: "2025-12-19",
    category: "animal",
  },
  {
    id: "p32",
    src: "https://artwork-hub.vercel.app/images/sheeps.jpg",
    tag: "sheep",
    alt: "Sheeps in the Field",
    ratio: 1.05,
    createtime: "2025-12-25",
    category: "animal",
  },
  {
    id: "p33",
    src: "https://artwork-hub.vercel.app/images/snowman2.jpg",
    tag: "snowman",
    alt: "Snowman with Scarf",
    ratio: 0.94,
    createtime: "2025-12-17",
  },
  {
    id: "p34",
    src: "https://artwork-hub.vercel.app/images/snowtemple.jpg",
    tag: "temple",
    alt: "Snow Temple",
    ratio: 0.35,
    objectFit: 'contain',
    createtime: "2025-12-25",
    category: "landscape",
  },
  {
    id: "p35",
    src: "https://artwork-hub.vercel.app/images/twocatswithmoon.jpg",
    tag: "cat",
    alt: "Two Cats Sitting under the Moon",
    ratio: 1.1,
    createtime: "2025-12-21",
    category: "animal",
  },
  {
    id: "p36",
    src: "https://artwork-hub.vercel.app/images/whitebird.jpg",
    tag: "crane",
    alt: "Red-frowned crane",
    ratio: 0.98,
    createtime: "2025-12-30",
    category: "animal",
  },
  {
    id: "p37",
    src: "https://artwork-hub.vercel.app/images/racon.jpg",
    tag: "raccoon",
    alt: "Animal Friends",
    ratio: 1.0,
    createtime: "2025-12-22",
    category: "animal",
  },
  {
    id: "p38",
    src: "https://artwork-hub.vercel.app/images/beach2.jpg",
    tag: "beach",
    alt: "Nice Beach",
    ratio: 0.48,
    objectFit: 'contain',
    createtime: "2026-1-10",
    category: "landscape",
  },
  {
    id: "p39",
    src: "https://artwork-hub.vercel.app/images/bluehairgirls.jpg",
    tag: "girl",
    alt: "blue hair girl",
    ratio: 1.2,
    createtime: "2026-1-5",
    category: "figure",
  },
  {
    id: "p40",
    src: "https://artwork-hub.vercel.app/images/fluffyball2.jpg",
    tag: "fluffy",
    alt: "fluffy ball friends",
    ratio: 0.8,
    createtime: "2026-1-2",
    category: "animal",
  },
  {
    id: "p41",
    src: "https://artwork-hub.vercel.app/images/girlcarry.jpg",
    tag: "girl",
    alt: "girl carrying small tree",
    ratio: 0.7,
    createtime: "2026-1-2",
    category: "figure",
  },
  {
    id: "p42",
    src: "https://artwork-hub.vercel.app/images/goodbear.jpg",
    tag: "bear",
    alt: "good bear",
    ratio: 1.0,
    createtime: "2026-1-3",
    category: "animal",
  },
  {
    id: "p43",
    src: "https://artwork-hub.vercel.app/images/mansea.jpg",
    tag: "sea",
    alt: "man by the sea",
    ratio: 1.1,
    createtime: "2025-12-22",
    category: "landscape",
  },
  {
    id: "p44",
    src: "https://artwork-hub.vercel.app/images/nightview2.jpg",
    tag: "night",
    alt: "peaceful night view",
    createtime: "2025-12-29",
    ratio: 1.5,
    category: "landscape",
  },
  {
    id: "p45",
    src: "https://artwork-hub.vercel.app/images/pinkbeach.jpg",
    tag: "beach",
    alt: "peaceful beach",
    objectFit: 'contain',
    ratio: 1.2,
    createtime: "2025-12-28",
    category: "landscape",
  },
  {
    id: "p46",
    src: "https://artwork-hub.vercel.app/images/sunset.jpg",
    tag: "sunset",
    alt: "sunset view",
    ratio: 1.2,
    createtime: "2025-12-18",
    category: "landscape",
  },
  {
    id: "p47",
    src: "https://artwork-hub.vercel.app/images/watermelon.jpg",
    tag: "watermelon duck",
    alt: "duck swimming in watermelon pool",
    ratio: 1.2,
    createtime: "2026-1-3",
    category: "fruit",
  },
  {
    id: "p48",
    src: "https://artwork-hub.vercel.app/images/whitedog.jpg",
    tag: "dog",
    alt: "white dog",
    ratio: 1.1,
    createtime: "2025-12-27",
    category: "animal",
  },
  {
    id: "p49",
    src: "https://artwork-hub.vercel.app/images/wintercabin.jpg",
    tag: "cabin",
    alt: "man walking in winter cabin",
    ratio: 1.15,
    createtime: "2025-12-18",
    category: "landscape",
  },

  {
    id: "p51",
    src: "https://artwork-hub.vercel.app/images/whales.jpg",
    tag: "whale",
    alt: "different whales",
    ratio: 1.2,
    createtime: "2026-1-4",
    category: "animal",
  },
  {
    id: "p52",
    src: "https://artwork-hub.vercel.app/images/hangingduck.jpg",
    tag: "duck",
    alt: "hanging duck",
    ratio: 1.2,
    createtime: "2025-12-15",
    category: "animal",
  },
  {
    id: "p53",
    src: "https://artwork-hub.vercel.app/images/banana.jpg",
    tag: "banana",
    alt: "cute banana",
    ratio: 1.2,
    createtime: "2025-12-15",
    category: "fruit",
  },
  {
    id: "p54",
    src: "https://artwork-hub.vercel.app/images/beach3.jpg",
    alt: "nice beach view",
    tag: "beach",
    ratio: 1.2,
    createtime: "2025-12-21",
    category: "landscape",
  },
  {
    id: "p55",
    src: "https://artwork-hub.vercel.app/images/blackdoor.jpg",
    alt: "black door",
    ratio: 1.1,
    tag: "garden door",
    createtime: "2025-12-21",
    category: "object",
  },
  {
    id: "p56",
    src: "https://artwork-hub.vercel.app/images/boysleep.jpg",
    alt: "boy sleeping",
    tag: "boy",
    ratio: 0.98,
    createtime: "2026-1-7",
    category: "figure",
  },
  {
    id: "p57",
    src: "https://artwork-hub.vercel.app/images/boysplay.jpg",
    tag: "boy",
    alt: "chase butterflies",
    ratio: 1.0,
    createtime: "2026-1-5",
    category: "landscape",
  },
  {
    id: "p58",
    src: "https://artwork-hub.vercel.app/images/colorsheep.jpg",
    tag: "sheep",
    alt: "sheep with colorful wool",
    ratio: 1.0,
    createtime: "2026-1-6",
    category: "animal",
  },
  {
    id: "p59",
    src: "https://artwork-hub.vercel.app/images/doggrass.jpg",
    alt: "dog in the grass",
    tag: "dog",
    ratio: 1.1,
    createtime: "2026-1-5",
    category: "animal",
  },
  {
    id: "p60",
    src: "https://artwork-hub.vercel.app/images/dogrunning.jpg",
    alt: "dog running",
    tag: "dog",
    ratio: 1.0,
    createtime: "2026-1-8",
    category: "animal",
  },
  {
    id: "p61",
    src: "https://artwork-hub.vercel.app/images/dogsleep.jpg",
    alt: "dog is sleeping",
    tag: "dog",
    ratio: 1.0,
    createtime: "2026-1-4",
    category: "animal",
  },
  {
    id: "p62",
    src: "https://artwork-hub.vercel.app/images/girlcat.jpg",
    alt: "girl is sitting with cat",
    tag: "girl",
    ratio: 1.4,
    createtime: "2026-1-6",
    category: "figure",
  },
  {
    id: "p63",
    src: "https://artwork-hub.vercel.app/images/girlhat.jpg",
    alt: "girl with hat",
    tag: "girl",
    ratio: 0.82,
    createtime: "2026-1-5",
    category: "figure",
  },
  {
    id: "p64",
    src: "https://artwork-hub.vercel.app/images/girlsmile.jpg",
    alt: "girl is smiling",
    tag: "girl",
    ratio: 1.0,
    createtime: "2026-1-9",
    category: "figure",
  },
  {
    id: "p65",
    src: "https://artwork-hub.vercel.app/images/horse.jpg",
    alt: "horse in the field",
    tag: "horse",
    ratio: 0.45,
    createtime: "2026-1-13",
    category: "animal",
  },
  {
    id: "p66",
    src: "https://artwork-hub.vercel.app/images/horse2026.jpg",
    alt: "horse celebration 2026",
    tag: "horse",
    ratio: 1.3,
    createtime: "2026-1-7",
    category: "animal",
  },
  {
    id: "p67",
    src: "https://artwork-hub.vercel.app/images/jiqimao.jpg",
    alt: "machine cat",
    tag: "cat",
    ratio: 1.0,
    createtime: "2026-1-5",
    category: "animal",
  },
  {
    id: "p68",
    src: "https://artwork-hub.vercel.app/images/lamp.jpg",  
    alt: "lamp",
    tag: "lamp",
    ratio: 0.9,
    createtime: "2026-1-5",
    category: "object",
  },
  {
    id: "p69",
    src: "https://artwork-hub.vercel.app/images/pinkcat.jpg",
    alt: "cat with glasses",
    tag: "cat",
    ratio: 1.1,
    createtime: "2026-1-4",
    category: "animal",
  },
  {
    id: "p70",
    src: "https://artwork-hub.vercel.app/images/planewindow.jpg",
    tag: "window beach view coconut trees",
    alt: "window seat view",
    ratio: 1.0,
    createtime: "2026-1-6",
    category: "landscape",
  },
  {
    id: "p71",
    src: "https://artwork-hub.vercel.app/images/sakuratree.jpg",
    tag: "sakura tree full of flowers",
    alt: "sakura tree",
    ratio: 1.5,
    createtime: "2026-1-6",
    category: "plant",
  },
  {
    id: "p72",
    src: "https://artwork-hub.vercel.app/images/snowcabin.jpg",
    tag: "cabin and snow",
    alt: "cabins in the snow",
    ratio: 1.0,
    createtime: "2026-1-7",
    category: "landscape",
  },
  {
    id: "p73",
    src: "https://artwork-hub.vercel.app/images/socks.jpg",
    tag: "sock",
    alt: "hanging socks",
    ratio: 1.0,
    createtime: "2026-1-14",
    category: "object",
  },
  {
    id: "p74",
    src: "https://artwork-hub.vercel.app/images/whitecatstar.jpg",
    tag: "cat with star",
    alt: "cat is playing with star",
    ratio: 1.08,
    createtime: "2026-1-14",
    category: "animal",
  },
  {
    id: "p75",
    src: "https://artwork-hub.vercel.app/images/whitesheep.jpg",
    tag: "sheep",
    alt: "white sheep",
    ratio: 1.0,
    createtime: "2026-1-11",
    category: "animal",
  },
  {
    id: "p76",
    src: "https://artwork-hub.vercel.app/images/fengche.jpg",
    tag: "windmill",
    alt: "windmill",
    ratio: 1.0,
    createtime: "2026-1-17",
    category: "landscape",
  },
  {
    id: "p77",
    src: "https://artwork-hub.vercel.app/images/guilin.jpg",
    tag: "guilin mountain",
    alt: "guilin landscape",
    ratio: 1.0,
    createtime: "2026-1-17",
    category: "landscape",
  },
  {
    id: "p78",
    src: "https://artwork-hub.vercel.app/images/colorfulcloth.jpg",
    tag: "girl",
    alt: "a girl with colorful cloth",
    ratio: 1.3,
    createtime: "2026-1-17",
    category: "figure",
  },
  {
    id: "p79",
    src: "https://artwork-hub.vercel.app/images/yellowgirl.jpg",
    tag: "girl",
    alt: "a girl in yellow dress",
    ratio: 1.0,
    createtime: "2026-1-30",
    category: "figure",
  },
  {
    id: "p80",
    src: "https://artwork-hub.vercel.app/images/catlookfish.jpg",
    tag: "cat",
    alt: "a cat looking at fish",
    ratio: 0.9,
    createtime: "2026-1-31",
    category: "animal",
  },
  {
    id: "p81",
    src: "https://artwork-hub.vercel.app/images/mermid.jpg",
    tag: "mermaid",
    alt: "mermid",
    ratio: 1,
    createtime: "2026-1-31",
    category: "figure",
  },
  {
    id: "p82",
    src: "https://artwork-hub.vercel.app/images/sunflower.jpg",
    tag: "sunflower",
    alt: "sunflower growing",
    ratio: 1.0,
    createtime: "2026-2-2",
    category: "plant",
  },
  {
    id: "p83",
    src: "https://artwork-hub.vercel.app/images/yellowflower.jpg",
    tag: "flower with houses",
    alt: "yellow flower with house",
    ratio: 1.5,
    createtime: "2026-2-2",
    category: "landscape",
  },
  {
    id: "p84",
    src: "https://artwork-hub.vercel.app/images/denglong.jpg",
    tag: "lantern",
    alt: "red lanterns",
    ratio: 1.0,
    createtime: "2026-2-3",
    category: "object",
  },
  {
    id: "p85",
    src: "https://artwork-hub.vercel.app/images/moon.jpg",
    tag: "moon and night with boat",
    alt: "full moon night",
    ratio: 0.7,
    createtime: "2026-2-3",
    category: "landscape",
  },
  {
    id: "p86",
    src: "https://artwork-hub.vercel.app/images/catfish.jpg",
    tag: "cat",
    alt: "cat and fish",
    ratio: 1.0,
    createtime: "2026-2-3",
    category: "animal",
  },
  {
    id: "p87",
    src: "https://artwork-hub.vercel.app/images/bluegirl.jpg",
    tag: "girl",
    alt: "blue hair girl",
    ratio: 1.0,
    createtime: "2026-2-3",
    category: "figure",
  },
  {
    id: "p88",
    src: "https://artwork-hub.vercel.app/images/park.jpg",
    tag: "park",
    alt: "park view",
    ratio: 0.6,
    createtime: "2025-12-19",
    category: "landscape",
  },
  {
    id: "p89",
    src: "https://artwork-hub.vercel.app/images/snail.jpg",
    tag: "snail",
    alt: "cute snail",
    ratio: 1.0,
    createtime: "2025-12-19",
    category: "animal",
  },
  {
    id: "p90",
    src: "https://artwork-hub.vercel.app/images/twocats.jpg",
    tag: "cat",
    alt: "two cats sitting together under the autumn tree",
    ratio: 1.1,
    createtime: "2025-12-16",
    category: "animal",
  },
  {
    id: "p91",
    src: "https://artwork-hub.vercel.app/images/bluecat.jpg",
    tag: "cat",
    alt: "blue cat",
    ratio: 1.0,
    createtime: "2025-12-16",
    category: "animal",
  },
  {
    id: "p92",
    src: "https://artwork-hub.vercel.app/images/beachview.jpg",
    tag: "beach",
    alt: "beach view",
    ratio: 1.0,
    createtime: "2025-12-15",
    category: "landscape",
  },
  {
    id: "p93",
    src: "https://artwork-hub.vercel.app/images/shipview.jpg",
    tag: "boat ship",
    alt: "ship view",
    ratio: 1.6,
    createtime: "2025-12-28",
    category: "landscape",
  },
  {
    id: "p94",
    src: "https://artwork-hub.vercel.app/images/moutainview.jpg",
    tag: "mountain",
    alt: "mountain view",
    ratio: 1.0,
    createtime: "2025-12-28",
    category: "landscape",
  },
  {
    id: "p95",
    src: "https://artwork-hub.vercel.app/images/xianrenzhang.jpg",
    tag: "plant",
    alt: "plant leaf",
    ratio: 1.0,
    createtime: "2025-12-24",
    category: "plant",
  },
  {
    id: "p96",
    src: "https://artwork-hub.vercel.app/images/sheepsplay.jpg",
    tag: "sheep",
    alt: "sheeps playing",
    ratio: 1.0,
    createtime: "2025-12-28",
    category: "animal",
  },
  {
    id: "p97",
    src: "https://artwork-hub.vercel.app/images/catlookingfirework.jpg",
    tag: "cat and firework",
    alt: "cat looking at firework",
    ratio: 1.0,
    createtime: "2026-1-6",
    category: "animal",
  },
  {
    id: "p98",
    src: "https://artwork-hub.vercel.app/images/humans.jpg",
    tag: "human and people",
    alt: "different humans",
    ratio: 1.0,
    createtime: "2025-12-23",
    category: "figure",
  },
  {
    id: "p99",
    src: "https://artwork-hub.vercel.app/images/changjinlu.jpg",
    tag: "giraffe",
    alt: "giraffe standing",
    ratio: 1.0,
    createtime: "2025-12-31",
    category: "animal",
  },
  {
    id: "p100",
    src: "https://artwork-hub.vercel.app/images/pugongying.jpg",
    tag: "dandelion",
    alt: "dandelion flower",
    ratio: 1.0,
    createtime: "2025-12-20",
    category: "plant",
  },
  {
    id: "p101",
    src: "https://artwork-hub.vercel.app/images/bigtree.jpg",
    tag: "tree",
    alt: "big tree",
    ratio: 1.6,
    createtime: "2025-12-29",
    category: "plant",
  },
  {
    id: "p102",
    src: "https://artwork-hub.vercel.app/images/book.jpg",
    tag: "book",
    alt: "book with tomato",
    ratio: 1.1,
    createtime: "2025-12-31",
    category: "object",
  },
  {
    id: "p103",
    src: "https://artwork-hub.vercel.app/images/sunset2.jpg",
    tag: "sunset",
    alt: "sunset sky",
    ratio: 1.0,
    createtime: "2025-12-30",
    category: "landscape",
  },
  {
    id: "p104",
    src: "https://artwork-hub.vercel.app/images/shuiguo.jpg",
    tag: "fruit",
    alt: "fruits world",
    ratio: 1.0,
    createtime: "2025-12-30",
    category: "fruit",
  },
  {
    id: "p105",
    src: "https://artwork-hub.vercel.app/images/xigua.jpg",
    tag: "watermelon",
    alt: "watermelon slice",
    ratio: 1.0,
    createtime: "2026-1-1",
    category: "fruit",
  },
  {
    id: "p106",
    src: "https://artwork-hub.vercel.app/images/newyear.jpg",
    tag: "newyear",
    alt: "new year 2026",
    ratio: 1.0,
    createtime: "2026-1-1",
    category: "figure",
  },

  {
    id: "p107",
    src: "https://artwork-hub.vercel.app/images/tank.jpg",
    tag: "tank",
    alt: "tank",
    ratio: 1.0,
    createtime: "2026-2-5",
    category: "object",
  },

  {
    id: "p108",
    src: "https://artwork-hub.vercel.app/images/awhitesheep.jpg",
    tag: "sheep",
    alt: "a white sheep",
    ratio: 1.07,
    createtime: "2026-02-06",
    category: "animal",
  },

  {
    id: "p109",
    src: "https://artwork-hub.vercel.app/images/aguineapig.jpg",
    tag: "guineapig",
    alt: "a guinea pig",
    ratio: 0.88,
    createtime: "2026-02-06",
    category: "animal",
  },

  {
    id: "p110",
    src: "https://artwork-hub.vercel.app/images/redcatholdtree.jpg",
    tag: "cat",
    alt: "a red cat holding a tree",
    ratio: 1.02,
    createtime: "2026-02-06",
    category: "animal",
  },

  {
    id: "p111",
    src: "https://artwork-hub.vercel.app/images/daisy.jpg",
    tag: "daisy",
    alt: "daisy",
    ratio: 1.01,
    createtime: "2026-02-06",
    category: "plant",
  },

  {
    id: "p112",
    src: "https://artwork-hub.vercel.app/images/daisyview.jpg",
    tag: "daisy flower",
    alt: "pink daisy view",
    ratio: 0.51,
    createtime: "2026-02-08",
    category: "plant",
  },

  {
    id: "p113",
    src: "https://artwork-hub.vercel.app/images/gateview.jpg",
    tag: "gate",
    alt: "gate view",
    ratio: 0.98,
    createtime: "2026-02-08",
    category: "landscape",
  },

  {
    id: "p114",
    src: "https://artwork-hub.vercel.app/images/greenview.jpg",
    tag: "green",
    alt: "green view",
    ratio: 1.02,
    createtime: "2026-02-08",
    category: "landscape",
  },

  {
    id: "p115",
    src: "https://artwork-hub.vercel.app/images/newyearnightview.jpg",
    tag: "night firework",
    alt: "new year night view",
    ratio: 0.54,
    createtime: "2026-02-08",
    category: "landscape",
  },

  {
    id: "p116",
    src: "https://artwork-hub.vercel.app/images/springviewhouse.jpg",
    tag: "house spring",
    alt: "spring view house",
    ratio: 0.49,
    createtime: "2026-02-08",
    category: "landscape",
  },

  {
    id: "p117",
    src: "https://artwork-hub.vercel.app/images/catwantfish.jpg",
    tag: "cat",
    alt: "cat wants fish",
    ratio: 0.55,
    createtime: "2026-02-10",
    category: "animal",
  },

  {
    id: "p118",
    src: "https://artwork-hub.vercel.app/images/girlstandingrass.jpg",
    tag: "girl",
    alt: "girl in grass",
    ratio: 1.0,
    createtime: "2026-02-10",
    category: "figure",
  },

  {
    id: "p119",
    src: "https://artwork-hub.vercel.app/images/ladder.jpg",
    tag: "ladder",
    alt: "ladder",
    ratio: 1.0,
    createtime: "2026-02-10",
    category: "object",
  },

  {
    id: "p120",
    src: "https://artwork-hub.vercel.app/images/willowwithboat.jpg",
    tag: "boat",
    alt: "willow with boat",
    ratio: 0.55,
    createtime: "2026-02-10",
    category: "landscape",
  },

  {
    id: "p121",
    src: "https://artwork-hub.vercel.app/images/windowmoutainview1.jpg",
    tag: "mountain view with sheep",
    alt: "window mountain view",
    ratio: 1.0,
    createtime: "2026-02-10",
    category: "landscape",
  },

  {
    id: "p122",
    src: "https://artwork-hub.vercel.app/images/winterplum.jpg",
    tag: "plum flower",
    alt: "winter plum",
    ratio: 0.51,
    createtime: "2026-02-10",
    category: "plant",
  },
  {
    id: "p123",
    src: "https://artwork-hub.vercel.app/images/fujiview1.jpg",
    tag: "fuji mountain",
    alt: "window view with fuji",
    ratio: 0.6,
    createtime: "2026-02-10",
    category: "landscape",
  },
  {
    id: "p124",
    src: "https://artwork-hub.vercel.app/images/s.jpg",
    tag: "letter humans",
    alt: "s word",
    ratio: 1.0,
    createtime: "2025-12-27",
    category: "object",
  },
  {
    id: "p125",
    src: "https://artwork-hub.vercel.app/images/boatboy.jpg",
    tag: "boat",
    alt: "boy is resting on the boat",
    ratio: 0.8,
    createtime: "2026-02-10",
    category: "landscape",
  },
  {
    id: "p126",
    src: "https://artwork-hub.vercel.app/images/birds.jpg",
    tag: "bird",
    alt: "pretty birds",
    ratio: 0.8,
    createtime: "2026-02-10",
    category: "animal",
  },
  {
    id: "p127",
    src: "https://artwork-hub.vercel.app/images/blackwithflower.jpg",
    tag: "flower",
    alt: "flower",
    ratio: 0.8,
    createtime: "2026-02-10",
    category: "plant",
  },
  {
    id: "p128",
    src: "https://artwork-hub.vercel.app/images/girlinrain.jpg",
    tag: "girl in rain",
    alt: "girl in rain",
    ratio: 0.8,
    createtime: "2026-2-11",
    category: "figure",
  },
  {
    id: "p129",
    src: "https://artwork-hub.vercel.app/images/fish2.jpg",
    tag: "fish",
    alt: "fish with ripples",
    ratio: 1.0,
    createtime: "2026-2-12",
    category: "animal",
  },

  {
    id: "p130",
    src: "https://artwork-hub.vercel.app/images/catwithflower.jpg",
    tag: "cat with flower",
    alt: "cat hiding in the flower",
    ratio: 1.0,
    createtime: "2026-2-12",
    category: "animal",
  },
  {
    id: "p131",
    src: "https://artwork-hub.vercel.app/images/catholdorange.jpg",
    tag: "cat with orange",
    alt: "cat holding orange",
    ratio: 1.0,
    createtime: "2026-2-12",
    category: "animal",
  },
  {
    id: "p132",
    src: "https://artwork-hub.vercel.app/images/cat-with-red-envelop.jpg",
    tag: "cat",
    alt: "cat with red envelop",
    ratio: 1.1,
    createtime: "2026-02-17",
    category: "animal",
  },
  {
    id: "p133",
    src: "https://artwork-hub.vercel.app/images/liondance.jpg",
    tag: "lion dance",
    alt: "lion dance celebration",
    ratio: 1.0,
    createtime: "2026-02-17",
    category: "object",
  },
  {
    id: "p134",
    src: "https://artwork-hub.vercel.app/images/snow-with-boat.jpg",
    tag: "snow boat",
    alt: "snow with boat",
    ratio: 0.5,
    createtime: "2026-02-17",
    category: "landscape",
  },
  {
    id: "p135",
    src: "https://artwork-hub.vercel.app/images/wintersweet-window.jpg",
    tag: "wintersweet",
    alt: "wintersweet window",
    ratio: 1.1,
    createtime: "2026-02-17",
    category: "plant",
  },
  {
    id: "p136",
    src: "https://artwork-hub.vercel.app/images/wishtree.jpg",
    tag: "wish tree",
    alt: "wish tree",
    ratio: 0.89,
    createtime: "2026-02-17",
    category: "plant",
  },
  




























];

export const galleryItems: GalleryItem[] = rawGalleryItems.map((item) => {
  const filename = item.src.split("/").pop();

  return {
    ...item,
    thumbSrc: item.thumbSrc ?? (filename ? `/images/thumbs/${filename}` : item.src),
  };
});
